// <auto-generated />
using System;
using MagicRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicRepositories.Migrations
{
    [DbContext(typeof(PortalContext))]
    partial class PortalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CardTypeMagicCard", b =>
                {
                    b.Property<Guid>("CardTypesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MagicCardsId")
                        .HasColumnType("char(36)");

                    b.HasKey("CardTypesId", "MagicCardsId");

                    b.HasIndex("MagicCardsId");

                    b.ToTable("CardTypeMagicCard");
                });

            modelBuilder.Entity("MagicAbilityMagicCard", b =>
                {
                    b.Property<Guid>("AbilitiesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CardsId")
                        .HasColumnType("char(36)");

                    b.HasKey("AbilitiesId", "CardsId");

                    b.HasIndex("CardsId");

                    b.ToTable("MagicAbilityMagicCard");
                });

            modelBuilder.Entity("MagicCardMagicLegality", b =>
                {
                    b.Property<Guid>("CardsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MagicLegalitiesId")
                        .HasColumnType("char(36)");

                    b.HasKey("CardsId", "MagicLegalitiesId");

                    b.HasIndex("MagicLegalitiesId");

                    b.ToTable("MagicCardMagicLegality");
                });

            modelBuilder.Entity("MagicCardSuperCardType", b =>
                {
                    b.Property<Guid>("MagicCardsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SuperCardTypesId")
                        .HasColumnType("char(36)");

                    b.HasKey("MagicCardsId", "SuperCardTypesId");

                    b.HasIndex("SuperCardTypesId");

                    b.ToTable("MagicCardSuperCardType");
                });

            modelBuilder.Entity("MtGDomain.Entities.CardType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CardType");
                });

            modelBuilder.Entity("MtGDomain.Entities.MagicAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MagicAbility");
                });

            modelBuilder.Entity("MtGDomain.Entities.MagicCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Cmc")
                        .HasColumnType("int");

                    b.Property<string>("CollectingNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsColorLess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMultiColor")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MagicSetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MultiverseId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MagicSetId");

                    b.ToTable("MagicCards");
                });

            modelBuilder.Entity("MtGDomain.Entities.MagicLegality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LegalityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MagicLegality");
                });

            modelBuilder.Entity("MtGDomain.Entities.MagicRuling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("MagicCardId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MagicCardId");

                    b.ToTable("MagicRuling");
                });

            modelBuilder.Entity("MtGDomain.Entities.MagicSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MagicSets");
                });

            modelBuilder.Entity("MtGDomain.Entities.SuperCardType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SuperCardType");
                });

            modelBuilder.Entity("CardTypeMagicCard", b =>
                {
                    b.HasOne("MtGDomain.Entities.CardType", null)
                        .WithMany()
                        .HasForeignKey("CardTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtGDomain.Entities.MagicCard", null)
                        .WithMany()
                        .HasForeignKey("MagicCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MagicAbilityMagicCard", b =>
                {
                    b.HasOne("MtGDomain.Entities.MagicAbility", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtGDomain.Entities.MagicCard", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MagicCardMagicLegality", b =>
                {
                    b.HasOne("MtGDomain.Entities.MagicCard", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtGDomain.Entities.MagicLegality", null)
                        .WithMany()
                        .HasForeignKey("MagicLegalitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MagicCardSuperCardType", b =>
                {
                    b.HasOne("MtGDomain.Entities.MagicCard", null)
                        .WithMany()
                        .HasForeignKey("MagicCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtGDomain.Entities.SuperCardType", null)
                        .WithMany()
                        .HasForeignKey("SuperCardTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MtGDomain.Entities.MagicCard", b =>
                {
                    b.HasOne("MtGDomain.Entities.MagicSet", "MagicSet")
                        .WithMany()
                        .HasForeignKey("MagicSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MagicSet");
                });

            modelBuilder.Entity("MtGDomain.Entities.MagicRuling", b =>
                {
                    b.HasOne("MtGDomain.Entities.MagicCard", null)
                        .WithMany("Rulings")
                        .HasForeignKey("MagicCardId");
                });

            modelBuilder.Entity("MtGDomain.Entities.MagicCard", b =>
                {
                    b.Navigation("Rulings");
                });
#pragma warning restore 612, 618
        }
    }
}
